#!/usr/bin/python3
#SPDX-FIleCopyrightTexy: 2023 Tsubokura Ryosuke
#SPDX-Lincense-Indentifier: BSD-3-Clause
import sys

ans=0
for line in sys.stdin:
	try:	
	    ans += int(line)
	except:
	    ans += float(line)

print(ans)
